name: Update CSV File

on:
  repository_dispatch:
    types: [submit_form]

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update CSV
        run: |
          echo "Name,Email" > data.csv
          echo "${{ github.event.client_payload.name }},${{ github.event.client_payload.email }}" >> data.csv

      - name: Commit CSV
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data.csv'
          message: 'Update data.csv with new form submission'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
        env:
          GITHUB_TOKEN: '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'
